### ISSUE TITLE
Rematch offers not recognized.

### ISSUE THREAD

**Issue by Curious2021** [SriMethan/liantichess#57]
After playing a game I hit the rematch button so I can play the next game with the opposite color. It doesn’t matter which game I choose…in my case I was playing Antipawns. Whenever the game was over…the rematch button doesn’t respond. I have to manually go out and select new game and manually choose the opposite color to play a new game. This needs a fix.

**Comment by SriMethan** [comment]
Should be fixed now, let me know if it does again.
